version: "3.9"

services:
  identity_db:
    container_name: identity_db
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    networks:
      - identity-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
      MONGO_INITDB_ROOT_PASSWORD: 'identity123'
      MONGO_INITDB_DATABASE: 'identity'
    volumes:
      - .docker/mongo/:/docker-entrypoint-initdb.d/

  java_app:
    container_name: identity_app
    image: identity-api
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - identity-net
    depends_on:
      - identity_db

networks:
  identity-net:
    driver: bridge
